// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Support both DATABASE_URL (recommended) and DIRECT_URL (legacy)
    url: process.env["DATABASE_URL"] ?? process.env["DIRECT_URL"],
  },
});
